{"date": ["1968-02-25 00:00:00"], "email": ["tsveta.karayancheva@parliament.bg"], "lang": ["Russian"], "name": ["TSVETA VALCHEVA KARAYANCHEVA"], "party": ["PP GERB"], "place": ["Bolyarovo, Bulgaria"], "prof": ["Engineer"]}
{"date": ["1970-04-10 00:00:00"], "email": ["daniela.maleshkova@parliament.bg"], "lang": ["German"], "name": ["DANIELA DIMITROVA MALESHKOVA"], "party": ["PP GERB"], "place": ["Septemvri, Bulgaria"], "prof": ["Lecturer"]}
{"date": ["1966-09-28 00:00:00"], "email": ["daniela.daritkova@parliament.bg"], "lang": [""], "name": ["DANIELA ANASTASOVA DARITKOVA-PRODANOVA"], "party": ["PP GERB"], "place": ["Plovdiv, Bulgaria"], "prof": [""]}
{"date": ["1978-08-09 00:00:00"], "email": ["daniel.yordanov@parliament.bg"], "lang": [""], "name": ["DANIEL PETKOV YORDANOV"], "party": ["BSP for Bulgaria"], "place": ["Dobrich, Bulgaria"], "prof": ["Agronomist"]}
{"date": ["1961-08-28 00:00:00"], "email": ["constantin.popov@parliament.bg"], "lang": ["English"], "name": ["CONSTANTIN VESELINOV POPOV"], "party": ["PP GERB"], "place": ["Sofia, Bulgaria"], "prof": ["Aviator"]}
{"date": ["1946-07-18 00:00:00"], "email": ["chavdar.velinov@parliament.bg"], "lang": ["Russian;Romanian"], "name": ["CHAVDAR YORDANOV VELINOV"], "party": ["BSP for Bulgaria"], "place": ["Dolni Vadin, Bulgaria"], "prof": [""]}
{"date": ["1965-06-17 00:00:00"], "email": ["byurhan.abazov@parliament.bg"], "lang": [""], "name": ["BYURHAN ILIYAZOV ABAZOV"], "party": ["Movement for Rights and Freedoms - MFR"], "place": ["Smirnenski, Bulgaria"], "prof": [""]}
{"date": ["1987-09-16 00:00:00"], "email": ["boryana.georgieva@parliament.bg"], "lang": ["English;Russian"], "name": ["BORYANA LYUBENOVA GEORGIEVA"], "party": ["Volya"], "place": ["Varna, Bulgaria"], "prof": ["Economist"]}
{"date": ["1972-02-11 00:00:00"], "email": ["borislav.borisov@parliament.bg"], "lang": ["English"], "name": ["BORISLAV IVANOV BORISOV"], "party": ["PP GERB"], "place": ["Yambol, Bulgaria"], "prof": ["pharmacist"]}
{"date": ["1965-07-02 00:00:00"], "email": ["boris.yachev@parliament.bg"], "lang": [""], "name": ["BORIS YANKOV YACHEV"], "party": ["United Patriots - NFSB, ATAKA and IMRO"], "place": ["Petrich, Bulgaria"], "prof": ["Economist;Lecturer"]}
{"date": ["1972-04-04 00:00:00"], "email": ["boris.borisov@parliament.bg"], "lang": ["Russian"], "name": ["BORIS VANGELOV BORISOV"], "party": ["United Patriots - NFSB, ATAKA and IMRO"], "place": ["Stara Zagora, Bulgaria"], "prof": ["Jurist;Historian"]}
{"date": ["1973-06-06 00:00:00"], "email": ["boris.karchev@parliament.bg"], "lang": ["English;Russian"], "name": ["BORIS PETKOV KARCHEV"], "party": ["PP GERB"], "place": ["Stara Zagora, Bulgaria"], "prof": ["Engineer"]}
{"date": ["1980-04-30 00:00:00"], "email": ["bogdan.botsev@parliament.bg"], "lang": ["English"], "name": ["BOGDAN EMILOV BOTSEV"], "party": ["BSP for Bulgaria"], "place": ["Sofia, Bulgaria"], "prof": ["Economist"]}
{"date": ["1968-05-03 00:00:00"], "email": ["atanas.kostadinov@parliament.bg"], "lang": ["English;Russian"], "name": ["ATANAS PETROV KOSTADINOV"], "party": ["BSP for Bulgaria"], "place": ["Sofia, Bulgaria"], "prof": ["Sociologist"]}
{"date": ["1976-04-28 00:00:00"], "email": ["atanas.tashkov@parliament.bg"], "lang": ["English"], "name": ["ATANAS IVANOV TASHKOV"], "party": ["PP GERB"], "place": ["Plovdiv, Bulgaria"], "prof": ["Engineer"]}
{"date": ["1971-07-09 00:00:00"], "email": ["asya.peeva@parliament.bg"], "lang": ["English;French;Russian;Greek"], "name": ["ASYA ATANASOVA PEEVA"], "party": ["PP GERB"], "place": ["Pomorie, Bulgaria"], "prof": ["Lecturer"]}
{"date": ["1974-12-15 00:00:00"], "email": ["zhelyo.boychev@parliament.bg"], "lang": [""], "name": ["ZHELYO IVANOV BOYCHEV"], "party": ["BSP for Bulgaria"], "place": ["Sofia, Bulgaria"], "prof": ["Economist"]}
{"date": ["1972-03-07 00:00:00"], "email": ["zapryan.yankov@parliament.bg"], "lang": ["Russian"], "name": ["ZAPRYAN VASILEV YANKOV"], "party": ["PP GERB"], "place": ["Plovdiv, Bulgaria"], "prof": ["Agronomist"]}
{"date": ["1957-08-28 00:00:00"], "email": ["yuliyan.papashimov@parliament.bg"], "lang": ["Russian"], "name": ["YULIYAN MIHAYLOV PAPASHIMOV"], "party": ["PP GERB"], "place": ["Yambol, Bulgaria"], "prof": ["Physician"]}
{"date": ["1975-05-05 00:00:00"], "email": ["yulian.angelov@parliament.bg"], "lang": ["English;Russian"], "name": ["YULIAN KRASTEV ANGELOV"], "party": ["United Patriots - NFSB, ATAKA and IMRO"], "place": ["Ruse, Bulgaria"], "prof": ["Economist"]}
{"date": ["1975-07-28 00:00:00"], "email": ["yordan.yordanov@parliament.bg"], "lang": ["Russian"], "name": ["YORDAN ILIEV YORDANOV"], "party": ["United Patriots - NFSB, ATAKA and IMRO"], "place": ["Dobrich, Bulgaria"], "prof": ["Lecturer"]}
{"date": ["1970-07-03 00:00:00"], "email": ["yordan.apostolov@parliament.bg"], "lang": ["Russian"], "name": ["YORDAN APOSTOLOV APOSTOLOV"], "party": ["United Patriots - NFSB, ATAKA and IMRO"], "place": ["Dobrich, Bulgaria"], "prof": ["Agronomist;Economist"]}
{"date": ["1990-02-11 00:00:00"], "email": ["yavor.bozhankov@parliament.bg"], "lang": ["English"], "name": ["YAVOR RUMENOV BOZHANKOV"], "party": ["BSP for Bulgaria"], "place": ["Gorna Oryahovitsa, Bulgaria"], "prof": ["Jurist"]}
{"date": ["1957-07-10 00:00:00"], "email": ["yavor.notev@parliament.bg"], "lang": [""], "name": ["YAVOR BOZHILOV NOTEV"], "party": ["United Patriots - NFSB, ATAKA and IMRO"], "place": ["Sofia, Bulgaria"], "prof": ["Jurist"]}
{"date": ["1973-12-29 00:00:00"], "email": ["vladislav.nikolov@parliament.bg"], "lang": ["English;Russian"], "name": ["VLADISLAV TOCHKOV NIKOLOV"], "party": ["PP GERB"], "place": ["Pleven, Bulgaria"], "prof": ["Economist"]}
{"date": ["1955-06-03 00:00:00"], "email": ["vladimir.toshev@parliament.bg"], "lang": ["English;Russian"], "name": ["VLADIMIR TSVETANOV TOSHEV"], "party": ["PP GERB"], "place": ["Ruzhintsi, Bulgaria"], "prof": ["Engineer"]}
{"date": ["1984-07-10 00:00:00"], "email": ["vladimir.valev@parliament.bg"], "lang": [""], "name": ["VLADIMIR SLAVCHEV VALEV"], "party": ["PP GERB"], "place": ["Varna, Bulgaria"], "prof": [""]}
{"date": ["1980-04-09 00:00:00"], "email": ["violeta.zheleva@parliament.bg"], "lang": ["English;Russian"], "name": ["VIOLETA RUSEVA ZHELEVA"], "party": ["BSP for Bulgaria"], "place": ["Dimitrovgrad, Bulgaria"], "prof": ["Engineer"]}
{"date": ["1951-12-14 00:00:00"], "email": ["vezhdi.rashidov@parliament.bg"], "lang": ["French;Russian;Turkish;Czech"], "name": ["VEZHDI LETIF RASHIDOV"], "party": ["PP GERB"], "place": ["Dimitrovgrad, Bulgaria"], "prof": ["artist"]}
{"date": ["1964-05-20 00:00:00"], "email": ["vessela.letcheva@parliament.bg"], "lang": ["English;Russian"], "name": ["VESSELA NIKOLAEVA LETCHEVA"], "party": ["BSP for Bulgaria"], "place": ["Veliko Tarnovo, Bulgaria"], "prof": ["manager"]}
{"date": ["1974-05-14 00:00:00"], "email": ["veska.nencheva@parliament.bg"], "lang": ["Russian"], "name": ["VESKA MARINOVA NENCHEVA"], "party": ["BSP for Bulgaria"], "place": ["Karlovo, Bulgaria"], "prof": ["Lecturer"]}
{"date": ["1956-07-31 00:00:00"], "email": ["venka.stoyanova@parliament.bg"], "lang": ["English;Russian"], "name": ["VENKA KONSTANTINOVA STOYANOVA"], "party": ["PP GERB"], "place": ["Ivanovo, Bulgaria"], "prof": ["Physician"]}
{"date": ["1967-09-02 00:00:00"], "email": ["velislava.krasteva@parliament.bg"], "lang": ["English;Russian"], "name": ["VELISLAVA IVANOVA KRASTEVA"], "party": ["Movement for Rights and Freedoms - MFR"], "place": ["Pleven, Bulgaria"], "prof": ["Journalist;Political scientist"]}
{"date": ["1986-06-24 00:00:00"], "email": ["vasil.tsvetkov@parliament.bg"], "lang": ["English"], "name": ["VASIL TSVETKOV TSVETKOV"], "party": ["PP GERB"], "place": ["Elin Pelin, Bulgaria"], "prof": ["Engineer"]}
{"date": ["1956-01-01 00:00:00"], "email": ["vasil.antonov@parliament.bg"], "lang": ["Russian"], "name": ["VASIL MILANOV ANTONOV"], "party": ["BSP for Bulgaria"], "place": ["Montana, Bulgaria"], "prof": ["Economist"]}
{"date": ["1965-10-24 00:00:00"], "email": ["valeri.jablyanov@parliament.bg"], "lang": [""], "name": ["VALERI MIRTCHEV JABLIANOV"], "party": ["BSP for Bulgaria"], "place": ["Sofia, Bulgaria"], "prof": [""]}
{"date": ["1958-02-13 00:00:00"], "email": ["valentina.naydenova@parliament.bg"], "lang": ["German;Russian"], "name": ["VALENTINA ALEKSANDROVA NAYDENOVA"], "party": ["BSP for Bulgaria"], "place": ["Troyan, Bulgaria"], "prof": ["Physician"]}
{"date": ["1966-03-15 00:00:00"], "email": ["valentin.milushev@parliament.bg"], "lang": ["English;Russian"], "name": ["VALENTIN MIRCHOV MILUSHEV"], "party": ["PP GERB"], "place": ["Samokov, Bulgaria"], "prof": ["Lecturer"]}
{"date": ["1958-02-06 00:00:00"], "email": ["valentin.kasabov@parliament.bg"], "lang": [""], "name": ["VALENTIN KIRILOV KASABOV"], "party": ["United Patriots - NFSB, ATAKA and IMRO"], "place": [", Bulgaria"], "prof": [""]}
{"date": ["1958-02-06 00:00:00"], "email": ["valentin.radev@parliament.bg"], "lang": ["English;Russian"], "name": ["VALENTIN IVANOV RADEV"], "party": ["PP GERB"], "place": ["Elin Pelin, Bulgaria"], "prof": ["Engineer;Economist"]}
{"date": ["1977-03-23 00:00:00"], "email": ["valentin.lambev@parliament.bg"], "lang": ["English"], "name": ["VALENTIN GEORGIEV LAMBEV"], "party": ["BSP for Bulgaria"], "place": ["Svishtov, Bulgaria"], "prof": ["Economist"]}
{"date": ["1971-08-09 00:00:00"], "email": ["valentin.a.nikolov@parliament.bg"], "lang": ["English;Russian"], "name": ["VALENTIN ALEKSIEV NIKOLOV"], "party": ["PP GERB"], "place": ["Gabrovo, Bulgaria"], "prof": ["Economist;Engineer"]}
{"date": ["1967-04-24 00:00:00"], "email": ["tsvetan.topchiev@parliament.bg"], "lang": ["Russian;Romanian"], "name": ["TSVETAN BORISOV TOPCHIEV"], "party": ["BSP for Bulgaria"], "place": ["Vidin, Bulgaria"], "prof": ["Physician"]}
{"date": ["1942-05-20 00:00:00"], "email": ["toma.tomov@parliament.bg"], "lang": ["English;Russian"], "name": ["TOMA NIKOLOV TOMOV"], "party": ["BSP for Bulgaria"], "place": ["Sofia, Bulgaria"], "prof": ["Journalist"]}
{"date": ["1980-10-10 00:00:00"], "email": ["toma.bikov@parliament.bg"], "lang": [""], "name": ["TOMA LYUBOMIROV BIKOV"], "party": ["PP GERB"], "place": ["Burgas, Bulgaria"], "prof": ["Political scientist"]}
{"date": ["1973-04-11 00:00:00"], "email": ["todor.baychev@parliament.bg"], "lang": ["English;Russian"], "name": ["TODOR BAYCHEV BAYCHEV"], "party": ["BSP for Bulgaria"], "place": ["Karnobat, Bulgaria"], "prof": ["Jurist"]}
{"date": ["1978-10-10 00:00:00"], "email": ["teodora.georgieva@parliament.bg"], "lang": ["English"], "name": ["TEODORA RADKOVA GEORGIEVA"], "party": ["PP GERB"], "place": ["Sofia, Bulgaria"], "prof": ["Economist"]}
{"date": ["1991-10-27 00:00:00"], "email": ["teodora.halacheva@parliament.bg"], "lang": ["English"], "name": ["TEODORA ATANASOVA HALACHEVA"], "party": ["BSP for Bulgaria"], "place": ["Plovdiv, Bulgaria"], "prof": ["manager;Political scientist"]}
{"date": ["1955-10-04 00:00:00"], "email": ["tasko.ermenkov@parliament.bg"], "lang": ["English;German;Russian"], "name": ["TASKO MIHAYLOV ERMENKOV"], "party": ["BSP for Bulgaria"], "place": ["Sofia, Bulgaria"], "prof": ["Lecturer;Economist"]}
{"date": ["1961-04-07 00:00:00"], "email": ["tanya.petrova@parliament.bg"], "lang": ["English;Russian"], "name": ["TANYA TODOROVA PETROVA"], "party": ["PP GERB"], "place": ["Veliko Tarnovo, Bulgaria"], "prof": ["Lecturer"]}
{"date": ["1973-03-28 00:00:00"], "email": ["taner.ali@parliament.bg"], "lang": ["English;Russian;Turkish"], "name": ["TANER MEHMED ALI"], "party": ["Movement for Rights and Freedoms - MFR"], "place": ["Targovishte, Bulgaria"], "prof": ["Lecturer"]}
{"date": ["1969-06-09 00:00:00"], "email": ["svetlana.angelova@parliament.bg"], "lang": ["English;Russian"], "name": ["SVETLANA ANGELOVA NAYDENOVA"], "party": ["PP GERB"], "place": ["Gorna Oryahovitsa, Bulgaria"], "prof": ["Financier"]}
{"date": ["1958-09-28 00:00:00"], "email": ["svetla.piralkova@parliament.bg"], "lang": ["English;Russian"], "name": ["SVETLA MARINOVA BACHVAROVA-PIRALKOVA"], "party": ["BSP for Bulgaria"], "place": ["Karnobat, Bulgaria"], "prof": ["Economist"]}
{"date": ["1960-09-16 00:00:00"], "email": ["stoyno.stoynov@parliament.bg"], "lang": [""], "name": ["STOYNO MITEV STOYNOV"], "party": ["PP GERB"], "place": [", Bulgaria"], "prof": [""]}
{"date": ["1971-09-01 00:00:00"], "email": ["stoyan.bozhinov@parliament.bg"], "lang": ["Russian"], "name": ["STOYAN RADKOV BOZHINOV"], "party": ["United Patriots - NFSB, ATAKA and IMRO"], "place": ["Parvomay, Bulgaria"], "prof": ["Jurist"]}
{"date": ["1982-09-24 00:00:00"], "email": ["stoyan.mirchev@parliament.bg"], "lang": ["English"], "name": ["STOIAN MIHAILOV MIRCHEV"], "party": ["BSP for Bulgaria"], "place": ["Sofia, Bulgaria"], "prof": ["Economist"]}
{"date": ["1986-06-14 00:00:00"], "email": ["stefan.burdzev@parliament.bg"], "lang": ["English"], "name": ["STEFAN IVANOV BURDZEV"], "party": ["BSP for Bulgaria"], "place": ["Pleven, Bulgaria"], "prof": ["Economist"]}
{"date": ["1988-02-28 00:00:00"], "email": ["stefan.apostolov@parliament.bg"], "lang": ["English"], "name": ["STEFAN APOSTOLOV APOSTOLOV"], "party": ["PP GERB"], "place": ["Blagoevgrad, Bulgaria"], "prof": ["Financier"]}
{"date": ["1985-05-30 00:00:00"], "email": ["stanislava.stoyanova@parliament.bg"], "lang": ["English"], "name": ["STANISLAVA KRASIMIROVA STOYANOVA"], "party": ["PP GERB"], "place": ["Dobrich, Bulgaria"], "prof": ["Lecturer;Economist"]}
{"date": ["1943-09-09 00:00:00"], "email": ["stanislav.stanilov@parliament.bg"], "lang": ["German;Russian"], "name": ["STANISLAV TODOROV STANILOV"], "party": ["United Patriots - NFSB, ATAKA and IMRO"], "place": ["Gabrovo, Bulgaria"], "prof": ["Historian;Archeologist"]}
{"date": ["1973-10-25 00:00:00"], "email": ["S.Ivanov@parliament.bg"], "lang": ["English"], "name": ["STANISLAV STOYANOV IVANOV"], "party": ["PP GERB"], "place": ["Karnobat, Bulgaria"], "prof": ["Economist"]}
{"date": ["1980-06-19 00:00:00"], "email": ["stanislav.stoyanov@parliament.bg"], "lang": ["English;Russian"], "name": ["STANISLAV IVANOV STOYANOV"], "party": ["PP GERB"], "place": ["Svishtov, Bulgaria"], "prof": ["Economist"]}
{"date": ["1980-12-21 00:00:00"], "email": ["stanislav.popov@parliament.bg"], "lang": ["English"], "name": ["STANISLAV IVANOV POPOV"], "party": ["PP GERB"], "place": ["Gotse Delchev, Bulgaria"], "prof": ["Economist"]}
{"date": ["1950-02-08 00:00:00"], "email": ["spas.panchev@parliament.bg"], "lang": ["English;Russian"], "name": ["SPAS YANEV PANCHEV"], "party": ["BSP for Bulgaria"], "place": ["Iliya, Bulgaria"], "prof": ["Engineer"]}
{"date": ["1953-01-18 00:00:00"], "email": ["spas.garnevski@parliament.bg"], "lang": [""], "name": ["SPAS GEORGIEV GARNEVSKI"], "party": ["PP GERB"], "place": ["Plovdiv, Bulgaria"], "prof": ["Economist"]}
{"date": ["1956-04-12 00:00:00"], "email": ["smilyana.nitova@parliament.bg"], "lang": ["French;Russian"], "name": ["SMILYANA NIKOLOVA NITOVA-KRASTEVA"], "party": ["BSP for Bulgaria"], "place": ["Haskovo, Bulgaria"], "prof": ["Jurist"]}
{"date": ["1952-05-24 00:00:00"], "email": ["slavi.netsov@parliament.bg"], "lang": ["Russian"], "name": ["SLAVI DICHEV NETSOV"], "party": ["Volya"], "place": ["Popitsa, Bulgaria"], "prof": ["Аutomotive and transport specialist"]}
{"date": ["1968-02-14 00:00:00"], "email": ["slavcho.atanasov@parliament.bg"], "lang": ["English;Russian"], "name": ["SLAVCHO STOEV ATANASOV"], "party": ["United Patriots - NFSB, ATAKA and IMRO"], "place": ["Karlovo, Bulgaria"], "prof": ["Jurist"]}
{"date": ["1955-01-25 00:00:00"], "email": ["simeon.simeonov@parliament.bg"], "lang": [""], "name": ["SIMEON HRISTOV SIMEONOV"], "party": ["Movement for Rights and Freedoms - MFR"], "place": [","], "prof": [""]}
{"date": ["1951-08-30 00:00:00"], "email": ["simeon.naydenov@parliament.bg"], "lang": ["Russian"], "name": ["SIMEON GEORGIEV NAYDENOV"], "party": ["Volya"], "place": ["Belogradets, Bulgaria"], "prof": ["Jurist"]}
{"date": ["1981-09-13 00:00:00"], "email": ["sevim.ali@parliament.bg"], "lang": [""], "name": ["SEVIM ISMAIL ALI"], "party": ["Movement for Rights and Freedoms - MFR"], "place": ["Aytos, Bulgaria"], "prof": ["Engineer"]}
{"date": ["1974-01-20 00:00:00"], "email": ["s.kichikov@parliament.bg"], "lang": [""], "name": ["SERGEY MANUSHOV KICHIKOV"], "party": ["Movement for Rights and Freedoms - MFR"], "place": ["Draginovo, Bulgaria"], "prof": [""]}
{"date": ["1965-03-29 00:00:00"], "email": ["ruslan.toshev@parliament.bg"], "lang": ["English;German;Russian"], "name": ["RUSLAN ZDRAVKOV TOSHEV"], "party": ["PP GERB"], "place": ["Varna, Bulgaria"], "prof": ["Physician;Jurist"]}
{"date": ["1956-10-04 00:00:00"], "email": ["rumen.gechev@parliament.bg"], "lang": ["English;Russian"], "name": ["RUMEN VASSILEV GECHEV"], "party": ["BSP for Bulgaria"], "place": ["CHerven bryag, Bulgaria"], "prof": ["Lecturer;Economist"]}
{"date": ["1965-09-15 00:00:00"], "email": ["rumen.genov@parliament.bg"], "lang": ["Russian"], "name": ["RUMEN PETROV GENOV"], "party": ["PP GERB"], "place": ["Shumen, Bulgaria"], "prof": ["Physician"]}
{"date": ["1969-04-19 00:00:00"], "email": ["rumen.georgiev@parliament.bg"], "lang": ["Russian"], "name": ["RUMEN NIKOLOV GEORGIEV"], "party": ["BSP for Bulgaria"], "place": ["Vratsa, Bulgaria"], "prof": ["Agronomist;Economist"]}
{"date": ["1955-03-28 00:00:00"], "email": ["rosen.malinov@parliament.bg"], "lang": ["Russian"], "name": ["ROSSEN MALINOV MALINOV"], "party": ["BSP for Bulgaria"], "place": ["Sofia, Bulgaria"], "prof": ["Historian;Lecturer"]}
{"date": ["1961-07-07 00:00:00"], "email": ["rosen.ivanov@parliament.bg"], "lang": ["Russian;Serbian/Croatian"], "name": ["ROSEN ZHIVKOV IVANOV"], "party": ["United Patriots - NFSB, ATAKA and IMRO"], "place": ["Kriva Bara, Bulgaria"], "prof": ["Technologist"]}
{"date": ["1957-04-12 00:00:00"], "email": ["ratalay@parliament.bg"], "lang": [""], "name": ["RAMADAN BAYRAM ATALAY"], "party": ["Movement for Rights and Freedoms - MFR"], "place": ["Madrevo, Bulgaria"], "prof": [""]}
{"date": ["1973-07-26 00:00:00"], "email": ["ralitsa.dobreva@parliament.bg"], "lang": ["Russian"], "name": ["RALITSA TRILKOVA DOBREVA"], "party": ["PP GERB"], "place": ["Pleven, Bulgaria"], "prof": ["Engineer-agronomist"]}
{"date": ["1985-07-22 00:00:00"], "email": ["radostin.tanev@parliament.bg"], "lang": ["English"], "name": ["RADOSTIN RADOSLAVOV TANEV"], "party": ["PP GERB"], "place": ["Stara Zagora, Bulgaria"], "prof": ["Economist"]}
{"date": ["1973-01-28 00:00:00"], "email": ["radoslava.chekanska@parliament.bg"], "lang": ["English"], "name": ["RADOSLAVA PLAMEN CHEKANSKA"], "party": ["PP GERB"], "place": ["Dupnitsa, Bulgaria"], "prof": ["Lecturer"]}
{"date": ["1977-02-06 00:00:00"], "email": ["radoslav.stoychev@parliament.bg"], "lang": ["English;Russian"], "name": ["RADOSLAV LYUBCHOV STOYCHEV"], "party": ["BSP for Bulgaria"], "place": ["Sofia, Bulgaria"], "prof": ["Economist"]}
{"date": ["1977-07-17 00:00:00"], "email": ["polina.hristova@parliament.bg"], "lang": ["English;Russian"], "name": ["POLINA TSVETOSLAVOVA TSANKOVA-HRISTOVA"], "party": ["Volya"], "place": ["Sofia, Bulgaria"], "prof": ["Engineer"]}
{"date": ["1986-07-29 00:00:00"], "email": ["polina.shishkova@parliament.bg"], "lang": ["English;French"], "name": ["POLINA ALEKSANDROVA SHISHKOVA"], "party": ["BSP for Bulgaria"], "place": ["Pazardzhik, Bulgaria"], "prof": ["Economist"]}
{"date": ["1976-01-16 00:00:00"], "email": ["mladen.shishkov@parliament.bg"], "lang": ["English;German;Russian"], "name": ["MLADEN NIKOLOV SHISHKOV"], "party": ["PP GERB"], "place": ["Plovdiv, Bulgaria"], "prof": ["Engineer"]}
{"date": ["1965-11-03 00:00:00"], "email": ["mitko.polihronov@parliament.bg"], "lang": ["Russian"], "name": ["MITKO KOSTADINOV POLIHRONOV"], "party": ["PP GERB"], "place": ["Madzharovo, Bulgaria"], "prof": ["Businessman"]}
{"date": ["1956-05-06 00:00:00"], "email": ["milko.nedyalkov@parliament.bg"], "lang": ["English;German;Russian"], "name": ["MILKO NEDYALKOV NEDYALKOV"], "party": ["BSP for Bulgaria"], "place": ["Lovech, Bulgaria"], "prof": ["Journalist"]}
{"date": ["1976-08-02 00:00:00"], "email": ["milena.damyanova@parliament.bg"], "lang": ["English;French;Russian;Hungarian;Chinese"], "name": ["MILENA TSVETANOVA DAMYANOVA"], "party": ["PP GERB"], "place": ["Silistra, Bulgaria"], "prof": ["Lecturer"]}
{"date": ["1961-05-04 00:00:00"], "email": ["milen.mihov@parliament.bg"], "lang": ["French;German;Russian"], "name": ["MILEN VASILEV MIHOV"], "party": ["United Patriots - NFSB, ATAKA and IMRO"], "place": ["Stara Zagora, Bulgaria"], "prof": ["Lecturer"]}
{"date": ["1991-05-18 00:00:00"], "email": ["mihail.hristov@parliament.bg"], "lang": ["English"], "name": ["MIHAIL IVAYLOV HRISTOV"], "party": ["BSP for Bulgaria"], "place": ["Pleven, Bulgaria"], "prof": ["Athlete"]}
{"date": ["1956-02-28 00:00:00"], "email": ["menda.stoyanova@parliament.bg"], "lang": ["English;Russian"], "name": ["MENDA KIRILOVA STOYANOVA"], "party": ["PP GERB"], "place": ["Sofia, Bulgaria"], "prof": ["Economist"]}
{"date": ["1979-09-03 00:00:00"], "email": ["martin.obreshkov@parliament.bg"], "lang": ["English;Russian"], "name": ["MARTIN STEFANOV OBRESHKOV"], "party": ["BSP for Bulgaria"], "place": ["Ruse, Bulgaria"], "prof": ["Architect"]}
{"date": ["1975-04-30 00:00:00"], "email": ["maria.tsvetkova@parliament.bg"], "lang": ["English"], "name": ["MARIYA YORDANOVA TSVETKOVA"], "party": ["United Patriots - NFSB, ATAKA and IMRO"], "place": ["Yambol, Bulgaria"], "prof": ["Journalist"]}
{"date": ["1973-01-05 00:00:00"], "email": ["mariya.ilieva@parliament.bg"], "lang": ["English;French;Russian;Italian"], "name": ["MARIYA YORDANOVA ILIEVA"], "party": ["PP GERB"], "place": ["Ruse, Bulgaria"], "prof": ["Economist"]}
{"date": ["1980-04-25 00:00:00"], "email": ["mariya.belova@parliament.bg"], "lang": [""], "name": ["MARIYA SHTEREVA BELOVA"], "party": ["PP GERB"], "place": ["Sliven, Bulgaria"], "prof": [""]}
{"date": ["1963-10-24 00:00:00"], "email": ["margarita.nikolova@parliament.bg"], "lang": ["French;Russian"], "name": ["MARGARITA NIKOLAEVA NIKOLOVA"], "party": ["United Patriots - NFSB, ATAKA and IMRO"], "place": ["Sofia, Bulgaria"], "prof": ["Economist;Engineer"]}
{"date": ["1960-06-14 00:00:00"], "email": ["manol.genov@parliament.bg"], "lang": ["English;Russian;Greek"], "name": ["MANOL TRIFONOV GENOV"], "party": ["BSP for Bulgaria"], "place": ["Asenovgrad, Bulgaria"], "prof": ["Economist;Lecturer"]}
{"date": ["1969-06-23 00:00:00"], "email": ["manoil.manev@parliament.bg"], "lang": ["English;Russian"], "name": ["MANOIL MINCHEV MANEV"], "party": ["PP GERB"], "place": ["Stara Zagora, Bulgaria"], "prof": ["Expert on Protection and Security;Lecturer"]}
{"date": ["1977-09-08 00:00:00"], "email": ["lyubomir.bonev@parliament.bg"], "lang": [""], "name": ["LYUBOMIR BOYKOV BONEV"], "party": ["BSP for Bulgaria"], "place": ["Pernik, Bulgaria"], "prof": ["Engineer"]}
{"date": ["1962-08-13 00:00:00"], "email": ["luchezar.ivanov@parliament.bg"], "lang": ["English;Russian"], "name": ["LUCHEZAR BOGOMILOV IVANOV"], "party": ["PP GERB"], "place": ["Sofia, Bulgaria"], "prof": ["Physician"]}
{"date": ["1950-06-23 00:00:00"], "email": ["liliana.radeva@parliament.bg"], "lang": ["English;French;Russian"], "name": ["LILIANA DRUMEVA RADEVA"], "party": ["PP GERB"], "place": ["Golyamo Vranovo, Bulgaria"], "prof": ["Lecturer"]}
{"date": ["1983-02-14 00:00:00"], "email": ["lalo.kirilov@parliament.bg"], "lang": ["English"], "name": ["LALO GEORGIEV KIRILOV"], "party": ["BSP for Bulgaria"], "place": ["Srednogorie, Bulgaria"], "prof": ["Economist"]}
{"date": ["1982-11-21 00:00:00"], "email": ["krum.zarkov@parliament.bg"], "lang": ["English;French"], "name": ["KRUM KOSTADINOV ZARKOV"], "party": ["BSP for Bulgaria"], "place": ["Sofia, Bulgaria"], "prof": ["Jurist"]}
{"date": ["1981-04-24 00:00:00"], "email": ["kristina.sidorova@parliament.bg"], "lang": ["English;German"], "name": ["KRISTINA MAKSIMOVA SIDOROVA"], "party": ["BSP for Bulgaria"], "place": ["Gabrovo, Bulgaria"], "prof": ["Engineer;Economist"]}
{"date": ["1983-11-04 00:00:00"], "email": ["krastina.taskova@parliament.bg"], "lang": ["Russian"], "name": ["KRASTINA NIKOLOVA TASKOVA"], "party": ["Volya"], "place": ["Dobrich, Bulgaria"], "prof": ["Economist"]}
{"date": ["1968-12-30 00:00:00"], "email": ["krasimir.sabev@parliament.bg"], "lang": ["English;Russian"], "name": ["KRASIMIR MITKOV SABEV"], "party": ["PP GERB"], "place": ["Madan, Bulgaria"], "prof": ["Physician"]}
{"date": ["1951-01-06 00:00:00"], "email": ["krasimir.velchev@parliament.bg"], "lang": ["Russian"], "name": ["KRASIMIR LYUBOMIROV VELCHEV"], "party": ["PP GERB"], "place": ["Sofia, Bulgaria"], "prof": ["manager"]}
{"date": ["1974-10-11 00:00:00"], "email": ["krasimir.bogdanov@parliament.bg"], "lang": ["Russian"], "name": ["KRASIMIR ILIEV BOGDANOV"], "party": ["United Patriots - NFSB, ATAKA and IMRO"], "place": ["Vratsa, Bulgaria"], "prof": ["Historian"]}
{"date": ["1974-12-11 00:00:00"], "email": ["krasimir.yankov@parliament.bg"], "lang": ["English;Russian"], "name": ["KRASIMIR HRISTOV YANKOV"], "party": ["BSP for Bulgaria"], "place": ["Stara Zagora, Bulgaria"], "prof": ["Economist"]}
{"date": ["1973-03-18 00:00:00"], "email": ["k.cipov@parliament.bg"], "lang": ["English;French;Russian;Serbian"], "name": ["KRASIMIR GEORGIEV TSIPOV"], "party": ["PP GERB"], "place": ["Plovdiv, Bulgaria"], "prof": ["Jurist"]}
{"date": ["1974-11-19 00:00:00"], "email": ["krasen.krastev@parliament.bg"], "lang": ["Russian"], "name": ["KRASEN GEORGIEV KRASTEV"], "party": ["PP GERB"], "place": ["Byala Slatina, Bulgaria"], "prof": ["Economist"]}
{"date": ["1969-01-16 00:00:00"], "email": ["korneliya.ninova@parliament.bg"], "lang": ["English;French"], "name": ["KORNELIYA PETROVA NINOVA"], "party": ["BSP for Bulgaria"], "place": ["Krushovitsa, Bulgaria"], "prof": ["Jurist"]}
{"date": ["1953-07-26 00:00:00"], "email": ["kolyo.milev@parliament.bg"], "lang": [""], "name": ["KOLYO YORDANOV MILEV"], "party": ["BSP for Bulgaria"], "place": ["Rudnik, Bulgaria"], "prof": ["Engineer"]}
{"date": ["1970-05-12 00:00:00"], "email": ["klavdya.gancheva@parliament.bg"], "lang": [""], "name": ["KLAVDIYA GEORGIEVA GRIGOROVA-GANCHEVA"], "party": ["PP GERB"], "place": ["Pleven, Bulgaria"], "prof": ["Engineer"]}
{"date": ["1952-12-14 00:00:00"], "email": ["kiril.kalfin@parliament.bg"], "lang": [""], "name": ["KIRIL BOYANOV KALFIN"], "party": ["PP GERB"], "place": ["Gorna Grashtitsa, Bulgaria"], "prof": ["Jurist"]}
{"name": ["EMIL MARINOV HRISTOV"], "date": ["1957-06-05 00:00:00"], "place": [","], "prof": [""], "lang": [""], "party": ["PP GERB"], "email": ["emil.hristov@parliament.bg"]}
{"name": ["TSVETA VALCHEVA KARAYANCHEVA"], "date": ["1968-02-25 00:00:00"], "place": ["Bolyarovo, Bulgaria"], "prof": ["Engineer"], "lang": ["Russian"], "party": ["PP GERB"], "email": ["tsveta.karayancheva@parliament.bg"]}
{"name": ["TSVETA VALCHEVA KARAYANCHEVA"], "date": ["1968-02-25 00:00:00"], "place": ["Bolyarovo, Bulgaria"], "prof": ["Engineer"], "lang": ["Russian"], "party": ["PP GERB"], "email": ["tsveta.karayancheva@parliament.bg"]}
{"name": ["TSVETA VALCHEVA KARAYANCHEVA"], "date": ["1968-02-25 00:00:00"], "place": ["Bolyarovo, Bulgaria"], "prof": ["Engineer"], "lang": ["Russian"], "party": ["PP GERB"], "email": ["tsveta.karayancheva@parliament.bg"]}
{"name": ["CONSTANTIN VESELINOV POPOV"], "date": ["1961-08-28 00:00:00"], "place": ["Sofia, Bulgaria"], "prof": ["Aviator"], "lang": ["English"], "party": ["PP GERB"], "email": ["constantin.popov@parliament.bg"]}
{"name": ["CHAVDAR YORDANOV VELINOV"], "date": ["1946-07-18 00:00:00"], "place": ["Dolni Vadin, Bulgaria"], "prof": [""], "lang": ["Russian;Romanian"], "party": ["BSP for Bulgaria"], "email": ["chavdar.velinov@parliament.bg"]}
{"name": ["BYURHAN ILIYAZOV ABAZOV"], "date": ["1965-06-17 00:00:00"], "place": ["Smirnenski, Bulgaria"], "prof": [""], "lang": [""], "party": ["Movement for Rights and Freedoms - MFR"], "email": ["byurhan.abazov@parliament.bg"]}
{"name": ["BORYANA LYUBENOVA GEORGIEVA"], "date": ["1987-09-16 00:00:00"], "place": ["Varna, Bulgaria"], "prof": ["Economist"], "lang": ["English;Russian"], "party": ["Volya"], "email": ["boryana.georgieva@parliament.bg"]}
{"name": ["BORISLAV IVANOV BORISOV"], "date": ["1972-02-11 00:00:00"], "place": ["Yambol, Bulgaria"], "prof": ["pharmacist"], "lang": ["English"], "party": ["PP GERB"], "email": ["borislav.borisov@parliament.bg"]}
{"name": ["BORIS YANKOV YACHEV"], "date": ["1965-07-02 00:00:00"], "place": ["Petrich, Bulgaria"], "prof": ["Economist;Lecturer"], "lang": [""], "party": ["United Patriots - NFSB, ATAKA and IMRO"], "email": ["boris.yachev@parliament.bg"]}
{"name": ["BORIS VANGELOV BORISOV"], "date": ["1972-04-04 00:00:00"], "place": ["Stara Zagora, Bulgaria"], "prof": ["Jurist;Historian"], "lang": ["Russian"], "party": ["United Patriots - NFSB, ATAKA and IMRO"], "email": ["boris.borisov@parliament.bg"]}
{"name": ["BORIS PETKOV KARCHEV"], "date": ["1973-06-06 00:00:00"], "place": ["Stara Zagora, Bulgaria"], "prof": ["Engineer"], "lang": ["English;Russian"], "party": ["PP GERB"], "email": ["boris.karchev@parliament.bg"]}
{"name": ["BOGDAN EMILOV BOTSEV"], "date": ["1980-04-30 00:00:00"], "place": ["Sofia, Bulgaria"], "prof": ["Economist"], "lang": ["English"], "party": ["BSP for Bulgaria"], "email": ["bogdan.botsev@parliament.bg"]}
{"name": ["ATANAS PETROV KOSTADINOV"], "date": ["1968-05-03 00:00:00"], "place": ["Sofia, Bulgaria"], "prof": ["Sociologist"], "lang": ["English;Russian"], "party": ["BSP for Bulgaria"], "email": ["atanas.kostadinov@parliament.bg"]}
{"name": ["ATANAS IVANOV TASHKOV"], "date": ["1976-04-28 00:00:00"], "place": ["Plovdiv, Bulgaria"], "prof": ["Engineer"], "lang": ["English"], "party": ["PP GERB"], "email": ["atanas.tashkov@parliament.bg"]}
{"name": ["ASYA ATANASOVA PEEVA"], "date": ["1971-07-09 00:00:00"], "place": ["Pomorie, Bulgaria"], "prof": ["Lecturer"], "lang": ["English;French;Russian;Greek"], "party": ["PP GERB"], "email": ["asya.peeva@parliament.bg"]}
{"name": ["ANTON KONSTANTINOV KUTEV"], "date": ["1968-09-13 00:00:00"], "place": ["Sofia, Bulgaria"], "prof": ["Economist"], "lang": ["English;Russian"], "party": ["BSP for Bulgaria"], "email": ["anton.kutev@parliament.bg"]}
{"name": ["ANNA VASILEVA ALEKSANDROVA"], "date": ["1972-02-25 00:00:00"], "place": ["Lom, Bulgaria"], "prof": ["Jurist"], "lang": [""], "party": ["PP GERB"], "email": ["anna.aleksandrova@parliament.bg"]}
{"name": ["ANNA NIKOLAEVA SLAVOVA"], "date": ["1978-01-05 00:00:00"], "place": ["Sofia, Bulgaria"], "prof": ["Economist"], "lang": ["English;Spanish"], "party": ["BSP for Bulgaria"], "email": ["anna.slavova@parliament.bg"]}
{"name": ["ZHELYO IVANOV BOYCHEV"], "date": ["1974-12-15 00:00:00"], "place": ["Sofia, Bulgaria"], "prof": ["Economist"], "lang": [""], "party": ["BSP for Bulgaria"], "email": ["zhelyo.boychev@parliament.bg"]}
{"name": ["ZAPRYAN VASILEV YANKOV"], "date": ["1972-03-07 00:00:00"], "place": ["Plovdiv, Bulgaria"], "prof": ["Agronomist"], "lang": ["Russian"], "party": ["PP GERB"], "email": ["zapryan.yankov@parliament.bg"]}
{"name": ["YULIYAN MIHAYLOV PAPASHIMOV"], "date": ["1957-08-28 00:00:00"], "place": ["Yambol, Bulgaria"], "prof": ["Physician"], "lang": ["Russian"], "party": ["PP GERB"], "email": ["yuliyan.papashimov@parliament.bg"]}
{"name": ["YULIAN KRASTEV ANGELOV"], "date": ["1975-05-05 00:00:00"], "place": ["Ruse, Bulgaria"], "prof": ["Economist"], "lang": ["English;Russian"], "party": ["United Patriots - NFSB, ATAKA and IMRO"], "email": ["yulian.angelov@parliament.bg"]}
{"name": ["YORDAN ILIEV YORDANOV"], "date": ["1975-07-28 00:00:00"], "place": ["Dobrich, Bulgaria"], "prof": ["Lecturer"], "lang": ["Russian"], "party": ["United Patriots - NFSB, ATAKA and IMRO"], "email": ["yordan.yordanov@parliament.bg"]}
{"name": ["YORDAN APOSTOLOV APOSTOLOV"], "date": ["1970-07-03 00:00:00"], "place": ["Dobrich, Bulgaria"], "prof": ["Agronomist;Economist"], "lang": ["Russian"], "party": ["United Patriots - NFSB, ATAKA and IMRO"], "email": ["yordan.apostolov@parliament.bg"]}
{"name": ["YAVOR RUMENOV BOZHANKOV"], "date": ["1990-02-11 00:00:00"], "place": ["Gorna Oryahovitsa, Bulgaria"], "prof": ["Jurist"], "lang": ["English"], "party": ["BSP for Bulgaria"], "email": ["yavor.bozhankov@parliament.bg"]}
{"name": ["YAVOR BOZHILOV NOTEV"], "date": ["1957-07-10 00:00:00"], "place": ["Sofia, Bulgaria"], "prof": ["Jurist"], "lang": [""], "party": ["United Patriots - NFSB, ATAKA and IMRO"], "email": ["yavor.notev@parliament.bg"]}
{"name": ["VLADISLAV TOCHKOV NIKOLOV"], "date": ["1973-12-29 00:00:00"], "place": ["Pleven, Bulgaria"], "prof": ["Economist"], "lang": ["English;Russian"], "party": ["PP GERB"], "email": ["vladislav.nikolov@parliament.bg"]}
{"name": ["VLADIMIR TSVETANOV TOSHEV"], "date": ["1955-06-03 00:00:00"], "place": ["Ruzhintsi, Bulgaria"], "prof": ["Engineer"], "lang": ["English;Russian"], "party": ["PP GERB"], "email": ["vladimir.toshev@parliament.bg"]}
{"name": ["VLADIMIR SLAVCHEV VALEV"], "date": ["1984-07-10 00:00:00"], "place": ["Varna, Bulgaria"], "prof": [""], "lang": [""], "party": ["PP GERB"], "email": ["vladimir.valev@parliament.bg"]}
{"name": ["VIOLETA RUSEVA ZHELEVA"], "date": ["1980-04-09 00:00:00"], "place": ["Dimitrovgrad, Bulgaria"], "prof": ["Engineer"], "lang": ["English;Russian"], "party": ["BSP for Bulgaria"], "email": ["violeta.zheleva@parliament.bg"]}
{"name": ["VEZHDI LETIF RASHIDOV"], "date": ["1951-12-14 00:00:00"], "place": ["Dimitrovgrad, Bulgaria"], "prof": ["artist"], "lang": ["French;Russian;Turkish;Czech"], "party": ["PP GERB"], "email": ["vezhdi.rashidov@parliament.bg"]}
{"name": ["VESSELA NIKOLAEVA LETCHEVA"], "date": ["1964-05-20 00:00:00"], "place": ["Veliko Tarnovo, Bulgaria"], "prof": ["manager"], "lang": ["English;Russian"], "party": ["BSP for Bulgaria"], "email": ["vessela.letcheva@parliament.bg"]}
{"name": ["VESKA MARINOVA NENCHEVA"], "date": ["1974-05-14 00:00:00"], "place": ["Karlovo, Bulgaria"], "prof": ["Lecturer"], "lang": ["Russian"], "party": ["BSP for Bulgaria"], "email": ["veska.nencheva@parliament.bg"]}
{"name": ["VENKA KONSTANTINOVA STOYANOVA"], "date": ["1956-07-31 00:00:00"], "place": ["Ivanovo, Bulgaria"], "prof": ["Physician"], "lang": ["English;Russian"], "party": ["PP GERB"], "email": ["venka.stoyanova@parliament.bg"]}
{"name": ["VELISLAVA IVANOVA KRASTEVA"], "date": ["1967-09-02 00:00:00"], "place": ["Pleven, Bulgaria"], "prof": ["Journalist;Political scientist"], "lang": ["English;Russian"], "party": ["Movement for Rights and Freedoms - MFR"], "email": ["velislava.krasteva@parliament.bg"]}
{"name": ["VASIL TSVETKOV TSVETKOV"], "date": ["1986-06-24 00:00:00"], "place": ["Elin Pelin, Bulgaria"], "prof": ["Engineer"], "lang": ["English"], "party": ["PP GERB"], "email": ["vasil.tsvetkov@parliament.bg"]}
{"name": ["VASIL MILANOV ANTONOV"], "date": ["1956-01-01 00:00:00"], "place": ["Montana, Bulgaria"], "prof": ["Economist"], "lang": ["Russian"], "party": ["BSP for Bulgaria"], "email": ["vasil.antonov@parliament.bg"]}
{"name": ["VALERI MIRTCHEV JABLIANOV"], "date": ["1965-10-24 00:00:00"], "place": ["Sofia, Bulgaria"], "prof": [""], "lang": [""], "party": ["BSP for Bulgaria"], "email": ["valeri.jablyanov@parliament.bg"]}
{"name": ["VALENTINA ALEKSANDROVA NAYDENOVA"], "date": ["1958-02-13 00:00:00"], "place": ["Troyan, Bulgaria"], "prof": ["Physician"], "lang": ["German;Russian"], "party": ["BSP for Bulgaria"], "email": ["valentina.naydenova@parliament.bg"]}
{"name": ["VALENTIN MIRCHOV MILUSHEV"], "date": ["1966-03-15 00:00:00"], "place": ["Samokov, Bulgaria"], "prof": ["Lecturer"], "lang": ["English;Russian"], "party": ["PP GERB"], "email": ["valentin.milushev@parliament.bg"]}
{"name": ["VALENTIN KIRILOV KASABOV"], "date": ["1958-02-06 00:00:00"], "place": [", Bulgaria"], "prof": [""], "lang": [""], "party": ["United Patriots - NFSB, ATAKA and IMRO"], "email": ["valentin.kasabov@parliament.bg"]}
{"name": ["VALENTIN IVANOV RADEV"], "date": ["1958-02-06 00:00:00"], "place": ["Elin Pelin, Bulgaria"], "prof": ["Engineer;Economist"], "lang": ["English;Russian"], "party": ["PP GERB"], "email": ["valentin.radev@parliament.bg"]}
{"name": ["VALENTIN GEORGIEV LAMBEV"], "date": ["1977-03-23 00:00:00"], "place": ["Svishtov, Bulgaria"], "prof": ["Economist"], "lang": ["English"], "party": ["BSP for Bulgaria"], "email": ["valentin.lambev@parliament.bg"]}
{"name": ["VALENTIN ALEKSIEV NIKOLOV"], "date": ["1971-08-09 00:00:00"], "place": ["Gabrovo, Bulgaria"], "prof": ["Economist;Engineer"], "lang": ["English;Russian"], "party": ["PP GERB"], "email": ["valentin.a.nikolov@parliament.bg"]}
{"name": ["TSVETAN BORISOV TOPCHIEV"], "date": ["1967-04-24 00:00:00"], "place": ["Vidin, Bulgaria"], "prof": ["Physician"], "lang": ["Russian;Romanian"], "party": ["BSP for Bulgaria"], "email": ["tsvetan.topchiev@parliament.bg"]}
{"name": ["TOMA NIKOLOV TOMOV"], "date": ["1942-05-20 00:00:00"], "place": ["Sofia, Bulgaria"], "prof": ["Journalist"], "lang": ["English;Russian"], "party": ["BSP for Bulgaria"], "email": ["toma.tomov@parliament.bg"]}
{"name": ["TOMA LYUBOMIROV BIKOV"], "date": ["1980-10-10 00:00:00"], "place": ["Burgas, Bulgaria"], "prof": ["Political scientist"], "lang": [""], "party": ["PP GERB"], "email": ["toma.bikov@parliament.bg"]}
{"name": ["TODOR BAYCHEV BAYCHEV"], "date": ["1973-04-11 00:00:00"], "place": ["Karnobat, Bulgaria"], "prof": ["Jurist"], "lang": ["English;Russian"], "party": ["BSP for Bulgaria"], "email": ["todor.baychev@parliament.bg"]}
{"name": ["TEODORA RADKOVA GEORGIEVA"], "date": ["1978-10-10 00:00:00"], "place": ["Sofia, Bulgaria"], "prof": ["Economist"], "lang": ["English"], "party": ["PP GERB"], "email": ["teodora.georgieva@parliament.bg"]}
{"name": ["TEODORA ATANASOVA HALACHEVA"], "date": ["1991-10-27 00:00:00"], "place": ["Plovdiv, Bulgaria"], "prof": ["manager;Political scientist"], "lang": ["English"], "party": ["BSP for Bulgaria"], "email": ["teodora.halacheva@parliament.bg"]}
{"name": ["TASKO MIHAYLOV ERMENKOV"], "date": ["1955-10-04 00:00:00"], "place": ["Sofia, Bulgaria"], "prof": ["Lecturer;Economist"], "lang": ["English;German;Russian"], "party": ["BSP for Bulgaria"], "email": ["tasko.ermenkov@parliament.bg"]}
{"name": ["TANYA TODOROVA PETROVA"], "date": ["1961-04-07 00:00:00"], "place": ["Veliko Tarnovo, Bulgaria"], "prof": ["Lecturer"], "lang": ["English;Russian"], "party": ["PP GERB"], "email": ["tanya.petrova@parliament.bg"]}
{"name": ["TANER MEHMED ALI"], "date": ["1973-03-28 00:00:00"], "place": ["Targovishte, Bulgaria"], "prof": ["Lecturer"], "lang": ["English;Russian;Turkish"], "party": ["Movement for Rights and Freedoms - MFR"], "email": ["taner.ali@parliament.bg"]}
{"name": ["SVETLANA ANGELOVA NAYDENOVA"], "date": ["1969-06-09 00:00:00"], "place": ["Gorna Oryahovitsa, Bulgaria"], "prof": ["Financier"], "lang": ["English;Russian"], "party": ["PP GERB"], "email": ["svetlana.angelova@parliament.bg"]}
{"name": ["SVETLA MARINOVA BACHVAROVA-PIRALKOVA"], "date": ["1958-09-28 00:00:00"], "place": ["Karnobat, Bulgaria"], "prof": ["Economist"], "lang": ["English;Russian"], "party": ["BSP for Bulgaria"], "email": ["svetla.piralkova@parliament.bg"]}
{"name": ["STOYNO MITEV STOYNOV"], "date": ["1960-09-16 00:00:00"], "place": [", Bulgaria"], "prof": [""], "lang": [""], "party": ["PP GERB"], "email": ["stoyno.stoynov@parliament.bg"]}
{"name": ["STOYAN RADKOV BOZHINOV"], "date": ["1971-09-01 00:00:00"], "place": ["Parvomay, Bulgaria"], "prof": ["Jurist"], "lang": ["Russian"], "party": ["United Patriots - NFSB, ATAKA and IMRO"], "email": ["stoyan.bozhinov@parliament.bg"]}
{"name": ["STOIAN MIHAILOV MIRCHEV"], "date": ["1982-09-24 00:00:00"], "place": ["Sofia, Bulgaria"], "prof": ["Economist"], "lang": ["English"], "party": ["BSP for Bulgaria"], "email": ["stoyan.mirchev@parliament.bg"]}
{"name": ["STEFAN IVANOV BURDZEV"], "date": ["1986-06-14 00:00:00"], "place": ["Pleven, Bulgaria"], "prof": ["Economist"], "lang": ["English"], "party": ["BSP for Bulgaria"], "email": ["stefan.burdzev@parliament.bg"]}
{"name": ["STEFAN APOSTOLOV APOSTOLOV"], "date": ["1988-02-28 00:00:00"], "place": ["Blagoevgrad, Bulgaria"], "prof": ["Financier"], "lang": ["English"], "party": ["PP GERB"], "email": ["stefan.apostolov@parliament.bg"]}
{"name": ["STANISLAVA KRASIMIROVA STOYANOVA"], "date": ["1985-05-30 00:00:00"], "place": ["Dobrich, Bulgaria"], "prof": ["Lecturer;Economist"], "lang": ["English"], "party": ["PP GERB"], "email": ["stanislava.stoyanova@parliament.bg"]}
{"name": ["STANISLAV TODOROV STANILOV"], "date": ["1943-09-09 00:00:00"], "place": ["Gabrovo, Bulgaria"], "prof": ["Historian;Archeologist"], "lang": ["German;Russian"], "party": ["United Patriots - NFSB, ATAKA and IMRO"], "email": ["stanislav.stanilov@parliament.bg"]}
{"name": ["STANISLAV STOYANOV IVANOV"], "date": ["1973-10-25 00:00:00"], "place": ["Karnobat, Bulgaria"], "prof": ["Economist"], "lang": ["English"], "party": ["PP GERB"], "email": ["S.Ivanov@parliament.bg"]}
{"name": ["STANISLAV IVANOV STOYANOV"], "date": ["1980-06-19 00:00:00"], "place": ["Svishtov, Bulgaria"], "prof": ["Economist"], "lang": ["English;Russian"], "party": ["PP GERB"], "email": ["stanislav.stoyanov@parliament.bg"]}
{"name": ["STANISLAV IVANOV POPOV"], "date": ["1980-12-21 00:00:00"], "place": ["Gotse Delchev, Bulgaria"], "prof": ["Economist"], "lang": ["English"], "party": ["PP GERB"], "email": ["stanislav.popov@parliament.bg"]}
{"name": ["SPAS YANEV PANCHEV"], "date": ["1950-02-08 00:00:00"], "place": ["Iliya, Bulgaria"], "prof": ["Engineer"], "lang": ["English;Russian"], "party": ["BSP for Bulgaria"], "email": ["spas.panchev@parliament.bg"]}
{"name": ["SPAS GEORGIEV GARNEVSKI"], "date": ["1953-01-18 00:00:00"], "place": ["Plovdiv, Bulgaria"], "prof": ["Economist"], "lang": [""], "party": ["PP GERB"], "email": ["spas.garnevski@parliament.bg"]}
{"name": ["SMILYANA NIKOLOVA NITOVA-KRASTEVA"], "date": ["1956-04-12 00:00:00"], "place": ["Haskovo, Bulgaria"], "prof": ["Jurist"], "lang": ["French;Russian"], "party": ["BSP for Bulgaria"], "email": ["smilyana.nitova@parliament.bg"]}
{"name": ["SLAVI DICHEV NETSOV"], "date": ["1952-05-24 00:00:00"], "place": ["Popitsa, Bulgaria"], "prof": ["Аutomotive and transport specialist"], "lang": ["Russian"], "party": ["Volya"], "email": ["slavi.netsov@parliament.bg"]}
{"name": ["SLAVCHO STOEV ATANASOV"], "date": ["1968-02-14 00:00:00"], "place": ["Karlovo, Bulgaria"], "prof": ["Jurist"], "lang": ["English;Russian"], "party": ["United Patriots - NFSB, ATAKA and IMRO"], "email": ["slavcho.atanasov@parliament.bg"]}
{"name": ["SIMEON HRISTOV SIMEONOV"], "date": ["1955-01-25 00:00:00"], "place": [","], "prof": [""], "lang": [""], "party": ["Movement for Rights and Freedoms - MFR"], "email": ["simeon.simeonov@parliament.bg"]}
{"name": ["SIMEON GEORGIEV NAYDENOV"], "date": ["1951-08-30 00:00:00"], "place": ["Belogradets, Bulgaria"], "prof": ["Jurist"], "lang": ["Russian"], "party": ["Volya"], "email": ["simeon.naydenov@parliament.bg"]}
{"name": ["SEVIM ISMAIL ALI"], "date": ["1981-09-13 00:00:00"], "place": ["Aytos, Bulgaria"], "prof": ["Engineer"], "lang": [""], "party": ["Movement for Rights and Freedoms - MFR"], "email": ["sevim.ali@parliament.bg"]}
{"name": ["SERGEY MANUSHOV KICHIKOV"], "date": ["1974-01-20 00:00:00"], "place": ["Draginovo, Bulgaria"], "prof": [""], "lang": [""], "party": ["Movement for Rights and Freedoms - MFR"], "email": ["s.kichikov@parliament.bg"]}
{"name": ["RUSLAN ZDRAVKOV TOSHEV"], "date": ["1965-03-29 00:00:00"], "place": ["Varna, Bulgaria"], "prof": ["Physician;Jurist"], "lang": ["English;German;Russian"], "party": ["PP GERB"], "email": ["ruslan.toshev@parliament.bg"]}
{"name": ["RUMEN VASSILEV GECHEV"], "date": ["1956-10-04 00:00:00"], "place": ["CHerven bryag, Bulgaria"], "prof": ["Lecturer;Economist"], "lang": ["English;Russian"], "party": ["BSP for Bulgaria"], "email": ["rumen.gechev@parliament.bg"]}
{"name": ["RUMEN PETROV GENOV"], "date": ["1965-09-15 00:00:00"], "place": ["Shumen, Bulgaria"], "prof": ["Physician"], "lang": ["Russian"], "party": ["PP GERB"], "email": ["rumen.genov@parliament.bg"]}
{"name": ["RUMEN NIKOLOV GEORGIEV"], "date": ["1969-04-19 00:00:00"], "place": ["Vratsa, Bulgaria"], "prof": ["Agronomist;Economist"], "lang": ["Russian"], "party": ["BSP for Bulgaria"], "email": ["rumen.georgiev@parliament.bg"]}
{"name": ["ROSSEN MALINOV MALINOV"], "date": ["1955-03-28 00:00:00"], "place": ["Sofia, Bulgaria"], "prof": ["Historian;Lecturer"], "lang": ["Russian"], "party": ["BSP for Bulgaria"], "email": ["rosen.malinov@parliament.bg"]}
{"name": ["ROSEN ZHIVKOV IVANOV"], "date": ["1961-07-07 00:00:00"], "place": ["Kriva Bara, Bulgaria"], "prof": ["Technologist"], "lang": ["Russian;Serbian/Croatian"], "party": ["United Patriots - NFSB, ATAKA and IMRO"], "email": ["rosen.ivanov@parliament.bg"]}
{"name": ["RAMADAN BAYRAM ATALAY"], "date": ["1957-04-12 00:00:00"], "place": ["Madrevo, Bulgaria"], "prof": [""], "lang": [""], "party": ["Movement for Rights and Freedoms - MFR"], "email": ["ratalay@parliament.bg"]}
{"name": ["RALITSA TRILKOVA DOBREVA"], "date": ["1973-07-26 00:00:00"], "place": ["Pleven, Bulgaria"], "prof": ["Engineer-agronomist"], "lang": ["Russian"], "party": ["PP GERB"], "email": ["ralitsa.dobreva@parliament.bg"]}
{"name": ["RADOSTIN RADOSLAVOV TANEV"], "date": ["1985-07-22 00:00:00"], "place": ["Stara Zagora, Bulgaria"], "prof": ["Economist"], "lang": ["English"], "party": ["PP GERB"], "email": ["radostin.tanev@parliament.bg"]}
{"name": ["RADOSLAVA PLAMEN CHEKANSKA"], "date": ["1973-01-28 00:00:00"], "place": ["Dupnitsa, Bulgaria"], "prof": ["Lecturer"], "lang": ["English"], "party": ["PP GERB"], "email": ["radoslava.chekanska@parliament.bg"]}
{"name": ["RADOSLAV LYUBCHOV STOYCHEV"], "date": ["1977-02-06 00:00:00"], "place": ["Sofia, Bulgaria"], "prof": ["Economist"], "lang": ["English;Russian"], "party": ["BSP for Bulgaria"], "email": ["radoslav.stoychev@parliament.bg"]}
{"name": ["POLINA TSVETOSLAVOVA TSANKOVA-HRISTOVA"], "date": ["1977-07-17 00:00:00"], "place": ["Sofia, Bulgaria"], "prof": ["Engineer"], "lang": ["English;Russian"], "party": ["Volya"], "email": ["polina.hristova@parliament.bg"]}
{"name": ["POLINA ALEKSANDROVA SHISHKOVA"], "date": ["1986-07-29 00:00:00"], "place": ["Pazardzhik, Bulgaria"], "prof": ["Economist"], "lang": ["English;French"], "party": ["BSP for Bulgaria"], "email": ["polina.shishkova@parliament.bg"]}
{"name": ["PLAMEN TRIFONOV HRISTOV"], "date": ["1977-06-28 00:00:00"], "place": ["Sofia, Bulgaria"], "prof": ["Engineer"], "lang": ["English;Russian"], "party": ["Volya"], "email": ["plamen.hristov@parliament.bg"]}
{"name": ["PLAMEN TACHEV PETROV"], "date": ["1964-03-29 00:00:00"], "place": ["CHerven bryag, Bulgaria"], "prof": ["Engineer"], "lang": ["English"], "party": ["PP GERB"], "email": ["plamen.tachev@parliament.bg"]}
{"name": ["PLAMEN IVANOV MANUSHEV"], "date": ["1954-04-16 00:00:00"], "place": ["General Toshevo, Bulgaria"], "prof": ["Officer;Engineer"], "lang": ["English;Russian"], "party": ["PP GERB"], "email": ["plamen.manushev@parliament.bg"]}
{"name": ["PLAMEN DULCHEV NUNEV"], "date": ["1956-11-24 00:00:00"], "place": ["Byala, Bulgaria"], "prof": [""], "lang": [""], "party": ["PP GERB"], "email": ["plamen.nunev@parliament.bg"]}
{"name": ["PETAR HRISTOV PETROV"], "date": ["1953-06-13 00:00:00"], "place": ["Sungurlare, Bulgaria"], "prof": ["Engineer"], "lang": ["English;German;Russian"], "party": ["United Patriots - NFSB, ATAKA and IMRO"], "email": ["petar.h.petrov@parliament.bg"]}
{"name": ["PETAR GEORGIEV KANEV"], "date": ["1953-12-18 00:00:00"], "place": ["Yambol, Bulgaria"], "prof": ["Engineer"], "lang": ["English;Russian"], "party": ["BSP for Bulgaria"], "email": ["petar.kanev@parliament.bg"]}
{"name": ["PAVEL DIMIRTOV SHOPOV"], "date": ["1955-09-13 00:00:00"], "place": ["Plovdiv, Bulgaria"], "prof": ["Jurist"], "lang": ["Russian"], "party": ["United Patriots - NFSB, ATAKA and IMRO"], "email": ["pavel.shopov@parliament.bg"]}
{"name": ["PAVEL ALEKSEEV HRISTOV"], "date": ["1983-09-12 00:00:00"], "place": ["Varna, Bulgaria"], "prof": ["IT specialist"], "lang": ["English;German;Russian"], "party": ["PP GERB"], "email": ["pavel.hristov@parliament.bg"]}
{"name": ["NONA KRASTEVA YOTOVA"], "date": ["1966-10-25 00:00:00"], "place": ["Sofia, Bulgaria"], "prof": ["Actress"], "lang": [""], "party": ["BSP for Bulgaria"], "email": ["nona.yotova@parliament.bg"]}
{"name": ["NIKOLINA PANAYOTOVA ANGELKOVA"], "date": ["1979-11-30 00:00:00"], "place": ["Krumovgrad, Bulgaria"], "prof": ["Jurist"], "lang": ["English;French;Russian;Spanish;Italian"], "party": ["PP GERB"], "email": ["nikolina.angelkova@parliament.bg"]}
{"name": ["NIKOLAY VESELINOV ALEKSANDROV"], "date": ["1986-01-11 00:00:00"], "place": ["Sofia, Bulgaria"], "prof": ["Economist"], "lang": ["English;Russian"], "party": ["United Patriots - NFSB, ATAKA and IMRO"], "email": ["nikolay.aleksandrov@parliament.bg"]}
{"name": ["NIKOLAY TSVETANOV SIRAKOV"], "date": ["1970-12-06 00:00:00"], "place": ["Veliko Tarnovo, Bulgaria"], "prof": ["actor"], "lang": ["German"], "party": ["PP GERB"], "email": ["nikolay.sirakov@parliament.bg"]}
{"name": ["NIKOLAY KRASTEV BOSHKILOV"], "date": ["1971-12-24 00:00:00"], "place": ["Blagoevgrad, Bulgaria"], "prof": [""], "lang": [""], "party": ["BSP for Bulgaria"], "email": ["nikolay.boshkilov@parliament.bg"]}
{"name": ["NIKOLAY IVANOV TSONKOV"], "date": ["1980-03-18 00:00:00"], "place": ["Sofia, Bulgaria"], "prof": ["Lecturer"], "lang": ["English;Russian"], "party": ["BSP for Bulgaria"], "email": ["nikolay.tsonkov@parliament.bg"]}
{"name": ["NIKOLAY GEORGIEV IVANOV"], "date": ["1968-10-23 00:00:00"], "place": ["Sofia, Bulgaria"], "prof": ["Engineer"], "lang": ["French;Russian"], "party": ["BSP for Bulgaria"], "email": ["nikolay.ivanov@parliament.bg"]}
{"name": ["NIKOLAY DIMITROV PENEV"], "date": ["1956-01-07 00:00:00"], "place": ["Yambol, Bulgaria"], "prof": ["Engineer"], "lang": ["German;Russian"], "party": ["BSP for Bulgaria"], "email": ["nikolay.penev@parliament.bg"]}
{"name": ["NIKOLAY ASENOV TISHEV"], "date": ["1975-09-14 00:00:00"], "place": ["Burgas, Bulgaria"], "prof": ["Economist"], "lang": ["English;Russian"], "party": ["BSP for Bulgaria"], "email": ["nikolay.tishev@parliament.bg"]}
{"name": ["NIKOLA ILIEV DINKOV"], "date": ["1957-03-16 00:00:00"], "place": ["Svilengrad, Bulgaria"], "prof": ["Engineer"], "lang": ["Russian"], "party": ["BSP for Bulgaria"], "email": ["nikola.dinkov@parliament.bg"]}
{"name": ["NELI RUSKOVA PETROVA"], "date": ["1969-01-17 00:00:00"], "place": ["Gorna Oryahovitsa, Bulgaria"], "prof": [""], "lang": ["Greek"], "party": ["PP GERB"], "email": ["neli.petrova@parliament.bg"]}
{"name": ["NADYA SPASOVA KLISURSKA-ZHEKOVA"], "date": ["1978-06-23 00:00:00"], "place": ["Pazardzhik, Bulgaria"], "prof": ["Jurist"], "lang": ["English"], "party": ["BSP for Bulgaria"], "email": ["nadya.zhekova@parliament.bg"]}
{"name": ["MUSTAFA SALI KARADAYI"], "date": ["1970-05-08 00:00:00"], "place": ["Borino, Bulgaria"], "prof": [""], "lang": [""], "party": ["Movement for Rights and Freedoms - MFR"], "email": ["mustafa.karadayi@parliament.bg"]}
{"name": ["MLADEN NIKOLOV SHISHKOV"], "date": ["1976-01-16 00:00:00"], "place": ["Plovdiv, Bulgaria"], "prof": ["Engineer"], "lang": ["English;German;Russian"], "party": ["PP GERB"], "email": ["mladen.shishkov@parliament.bg"]}
{"name": ["MITKO KOSTADINOV POLIHRONOV"], "date": ["1965-11-03 00:00:00"], "place": ["Madzharovo, Bulgaria"], "prof": ["Businessman"], "lang": ["Russian"], "party": ["PP GERB"], "email": ["mitko.polihronov@parliament.bg"]}
{"name": ["MILKO NEDYALKOV NEDYALKOV"], "date": ["1956-05-06 00:00:00"], "place": ["Lovech, Bulgaria"], "prof": ["Journalist"], "lang": ["English;German;Russian"], "party": ["BSP for Bulgaria"], "email": ["milko.nedyalkov@parliament.bg"]}
{"name": ["MILENA TSVETANOVA DAMYANOVA"], "date": ["1976-08-02 00:00:00"], "place": ["Silistra, Bulgaria"], "prof": ["Lecturer"], "lang": ["English;French;Russian;Hungarian;Chinese"], "party": ["PP GERB"], "email": ["milena.damyanova@parliament.bg"]}
{"name": ["MILEN VASILEV MIHOV"], "date": ["1961-05-04 00:00:00"], "place": ["Stara Zagora, Bulgaria"], "prof": ["Lecturer"], "lang": ["French;German;Russian"], "party": ["United Patriots - NFSB, ATAKA and IMRO"], "email": ["milen.mihov@parliament.bg"]}
{"name": ["MIHAIL IVAYLOV HRISTOV"], "date": ["1991-05-18 00:00:00"], "place": ["Pleven, Bulgaria"], "prof": ["Athlete"], "lang": ["English"], "party": ["BSP for Bulgaria"], "email": ["mihail.hristov@parliament.bg"]}
{"name": ["MENDA KIRILOVA STOYANOVA"], "date": ["1956-02-28 00:00:00"], "place": ["Sofia, Bulgaria"], "prof": ["Economist"], "lang": ["English;Russian"], "party": ["PP GERB"], "email": ["menda.stoyanova@parliament.bg"]}
{"name": ["MARTIN STEFANOV OBRESHKOV"], "date": ["1979-09-03 00:00:00"], "place": ["Ruse, Bulgaria"], "prof": ["Architect"], "lang": ["English;Russian"], "party": ["BSP for Bulgaria"], "email": ["martin.obreshkov@parliament.bg"]}
{"name": ["MARIYA YORDANOVA TSVETKOVA"], "date": ["1975-04-30 00:00:00"], "place": ["Yambol, Bulgaria"], "prof": ["Journalist"], "lang": ["English"], "party": ["United Patriots - NFSB, ATAKA and IMRO"], "email": ["maria.tsvetkova@parliament.bg"]}
{"name": ["MARIYA YORDANOVA ILIEVA"], "date": ["1973-01-05 00:00:00"], "place": ["Ruse, Bulgaria"], "prof": ["Economist"], "lang": ["English;French;Russian;Italian"], "party": ["PP GERB"], "email": ["mariya.ilieva@parliament.bg"]}
{"name": ["MARIYA SHTEREVA BELOVA"], "date": ["1980-04-25 00:00:00"], "place": ["Sliven, Bulgaria"], "prof": [""], "lang": [""], "party": ["PP GERB"], "email": ["mariya.belova@parliament.bg"]}
{"name": ["MANOIL MINCHEV MANEV"], "date": ["1969-06-23 00:00:00"], "place": ["Stara Zagora, Bulgaria"], "prof": ["Expert on Protection and Security;Lecturer"], "lang": ["English;Russian"], "party": ["PP GERB"], "email": ["manoil.manev@parliament.bg"]}
{"name": ["LYUBOMIR BOYKOV BONEV"], "date": ["1977-09-08 00:00:00"], "place": ["Pernik, Bulgaria"], "prof": ["Engineer"], "lang": [""], "party": ["BSP for Bulgaria"], "email": ["lyubomir.bonev@parliament.bg"]}
{"name": ["LUCHEZAR BOGOMILOV IVANOV"], "date": ["1962-08-13 00:00:00"], "place": ["Sofia, Bulgaria"], "prof": ["Physician"], "lang": ["English;Russian"], "party": ["PP GERB"], "email": ["luchezar.ivanov@parliament.bg"]}
{"name": ["LILIANA DRUMEVA RADEVA"], "date": ["1950-06-23 00:00:00"], "place": ["Golyamo Vranovo, Bulgaria"], "prof": ["Lecturer"], "lang": ["English;French;Russian"], "party": ["PP GERB"], "email": ["liliana.radeva@parliament.bg"]}
{"name": ["LALO GEORGIEV KIRILOV"], "date": ["1983-02-14 00:00:00"], "place": ["Srednogorie, Bulgaria"], "prof": ["Economist"], "lang": ["English"], "party": ["BSP for Bulgaria"], "email": ["lalo.kirilov@parliament.bg"]}
{"name": ["KRUM KOSTADINOV ZARKOV"], "date": ["1982-11-21 00:00:00"], "place": ["Sofia, Bulgaria"], "prof": ["Jurist"], "lang": ["English;French"], "party": ["BSP for Bulgaria"], "email": ["krum.zarkov@parliament.bg"]}
{"name": ["KRISTINA MAKSIMOVA SIDOROVA"], "date": ["1981-04-24 00:00:00"], "place": ["Gabrovo, Bulgaria"], "prof": ["Engineer;Economist"], "lang": ["English;German"], "party": ["BSP for Bulgaria"], "email": ["kristina.sidorova@parliament.bg"]}
{"name": ["KRASTINA NIKOLOVA TASKOVA"], "date": ["1983-11-04 00:00:00"], "place": ["Dobrich, Bulgaria"], "prof": ["Economist"], "lang": ["Russian"], "party": ["Volya"], "email": ["krastina.taskova@parliament.bg"]}
{"name": ["KRASIMIR MITKOV SABEV"], "date": ["1968-12-30 00:00:00"], "place": ["Madan, Bulgaria"], "prof": ["Physician"], "lang": ["English;Russian"], "party": ["PP GERB"], "email": ["krasimir.sabev@parliament.bg"]}
{"name": ["KRASIMIR LYUBOMIROV VELCHEV"], "date": ["1951-01-06 00:00:00"], "place": ["Sofia, Bulgaria"], "prof": ["manager"], "lang": ["Russian"], "party": ["PP GERB"], "email": ["krasimir.velchev@parliament.bg"]}
{"name": ["KRASIMIR ILIEV BOGDANOV"], "date": ["1974-10-11 00:00:00"], "place": ["Vratsa, Bulgaria"], "prof": ["Historian"], "lang": ["Russian"], "party": ["United Patriots - NFSB, ATAKA and IMRO"], "email": ["krasimir.bogdanov@parliament.bg"]}
{"name": ["KRASIMIR HRISTOV YANKOV"], "date": ["1974-12-11 00:00:00"], "place": ["Stara Zagora, Bulgaria"], "prof": ["Economist"], "lang": ["English;Russian"], "party": ["BSP for Bulgaria"], "email": ["krasimir.yankov@parliament.bg"]}
{"name": ["KRASIMIR GEORGIEV TSIPOV"], "date": ["1973-03-18 00:00:00"], "place": ["Plovdiv, Bulgaria"], "prof": ["Jurist"], "lang": ["English;French;Russian;Serbian"], "party": ["PP GERB"], "email": ["k.cipov@parliament.bg"]}
{"name": ["KRASEN GEORGIEV KRASTEV"], "date": ["1974-11-19 00:00:00"], "place": ["Byala Slatina, Bulgaria"], "prof": ["Economist"], "lang": ["Russian"], "party": ["PP GERB"], "email": ["krasen.krastev@parliament.bg"]}
{"name": ["KORNELIYA PETROVA NINOVA"], "date": ["1969-01-16 00:00:00"], "place": ["Krushovitsa, Bulgaria"], "prof": ["Jurist"], "lang": ["English;French"], "party": ["BSP for Bulgaria"], "email": ["korneliya.ninova@parliament.bg"]}
{"name": ["KOLYO YORDANOV MILEV"], "date": ["1953-07-26 00:00:00"], "place": ["Rudnik, Bulgaria"], "prof": ["Engineer"], "lang": [""], "party": ["BSP for Bulgaria"], "email": ["kolyo.milev@parliament.bg"]}
{"name": ["KLAVDIYA GEORGIEVA GRIGOROVA-GANCHEVA"], "date": ["1970-05-12 00:00:00"], "place": ["Pleven, Bulgaria"], "prof": ["Engineer"], "lang": [""], "party": ["PP GERB"], "email": ["klavdya.gancheva@parliament.bg"]}
{"name": ["KIRIL BOYANOV KALFIN"], "date": ["1952-12-14 00:00:00"], "place": ["Gorna Grashtitsa, Bulgaria"], "prof": ["Jurist"], "lang": [""], "party": ["PP GERB"], "email": ["kiril.kalfin@parliament.bg"]}
{"name": ["KALIN NIKOLOV POPOVSKI"], "date": ["1965-03-06 00:00:00"], "place": ["Sofia, Bulgaria"], "prof": ["Physician"], "lang": ["English;Russian"], "party": ["United Patriots - NFSB, ATAKA and IMRO"], "email": ["kalin.popovski@parliament.bg"]}
{"name": ["KALIN LUBENOV VELIOV"], "date": ["1973-06-18 00:00:00"], "place": ["Sofia, Bulgaria"], "prof": ["musician"], "lang": ["English;Russian"], "party": ["PP GERB"], "email": ["kalin.veliov@parliament.bg"]}
{"name": ["KALIN DIMITROV VASILEV"], "date": ["1976-02-27 00:00:00"], "place": ["Lukovit, Bulgaria"], "prof": ["Economist"], "lang": [""], "party": ["PP GERB"], "email": ["kalin.vasilev@parliament.bg"]}
{"name": ["JORDAN KIRILOV TZONEV"], "date": ["1956-10-05 00:00:00"], "place": ["Karapelit, Bulgaria"], "prof": ["Economist"], "lang": ["English;Russian"], "party": ["Movement for Rights and Freedoms - MFR"], "email": ["jordan.tsonev@parliament.bg"]}
{"name": ["IVO ANGELOV HRISTOV"], "date": ["1966-09-05 00:00:00"], "place": ["Kiev, Ukrayna"], "prof": ["Lecturer;Sociologist"], "lang": ["English;Russian"], "party": ["BSP for Bulgaria"], "email": ["ivo.hristov@parliament.bg"]}
{"name": ["IVELINA VESSELINOVA VASSILEVA"], "date": ["1969-10-08 00:00:00"], "place": ["Burgas, Bulgaria"], "prof": ["Project Management Expert"], "lang": ["English;Russian"], "party": ["PP GERB"], "email": ["ivelina.vasileva@parliament.bg"]}
{"name": ["IVAN VALENTINOV IVANOV"], "date": ["1975-08-13 00:00:00"], "place": ["Shumen, Bulgaria"], "prof": ["Historian;Jurist"], "lang": ["English;German;Russian"], "party": ["BSP for Bulgaria"], "email": ["i.ivanov@parliament.bg"]}
{"name": ["IVAN TODOROV IBRISHIMOV"], "date": ["1977-01-26 00:00:00"], "place": ["Dupnitsa, Bulgaria"], "prof": ["Physician"], "lang": ["English;Russian"], "party": ["BSP for Bulgaria"], "email": ["ivan.ibrishimov@parliament.bg"]}
{"name": ["IVAN STEFANOV VALKOV"], "date": ["1965-05-22 00:00:00"], "place": ["Pomorie, Bulgaria"], "prof": ["Engineer"], "lang": ["German;Russian"], "party": ["PP GERB"], "email": ["ivan.valkov@parliament.bg"]}
{"name": ["IVAN NIKOLOV MIHOVSKI"], "date": ["1980-06-20 00:00:00"], "place": ["Lovech, Bulgaria"], "prof": [""], "lang": [""], "party": ["PP GERB"], "email": ["ivan.mihovski@parliament.bg"]}
{"name": ["IVAN IVAYLOV CHENCHEV"], "date": ["1976-08-05 00:00:00"], "place": ["Sofia, Bulgaria"], "prof": ["Journalist"], "lang": ["English;Russian"], "party": ["BSP for Bulgaria"], "email": ["ivan.chenchev@parliament.bg"]}
{"name": ["IVAN DIMOV IVANOV"], "date": ["1965-08-08 00:00:00"], "place": ["Dragoevo, Bulgaria"], "prof": ["Philologist"], "lang": ["English;Russian"], "party": ["BSP for Bulgaria"], "email": ["ivan.ivanov@parliament.bg"]}
{"name": ["ISKREN VASILEV VESELINOV"], "date": ["1972-03-14 00:00:00"], "place": ["Ruse, Bulgaria"], "prof": ["Jurist;Engineer"], "lang": ["English;Russian"], "party": ["United Patriots - NFSB, ATAKA and IMRO"], "email": ["iskren.veselinov@parliament.bg"]}
